apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  spring-boot-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/EziamaUgonna/Jenkins_argocd.git
    targetRevision: HEAD
    path: spring-boot-app-manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
